name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: read
  checks: write
jobs:
  test:
    timeout-minutes: 5
    runs-on: blacksmith-4vcpu-ubuntu-2404
    env:
      CI: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Enable Corepack
        shell: bash
        run: corepack enable

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: yarn

      - name: Install Ruby for Test App
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: ./test/dummy

      - name: Setup Test App
        working-directory: ./test/dummy
        run: bin/setup --skip-server

      - name: Install Turbo-Confirm Dependencies
        run: yarn install

      - name: Check Playwright Cache
        uses: actions/cache@v5
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install Playwright OS dependencies
        run: yarn playwright install-deps

      - name: Setup Playwright
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: yarn playwright install chromium firefox webkit

      - name: Run Test Suite
        run: yarn playwright test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            test-results/results.json
            test-results/.last-run.json
          include-hidden-files: true
          retention-days: 30
